### ISSUE TITLE
Experiment results in the spllited dataset.

### ISSUE THREAD

**Issue by qq472220372** [evison/JRL#4]
I set the params as the paper introducted. 
Category | net_struct | epoch | rate_emb_size  | loss | LRS@10 | Recall@10 | Precision@10 | NDCG@10 | Hit@10 | LR | img_w | emb_size | grad_norm
Beauty_CIKM2017 | default | 20 | 200 | 2080.8 | 0.01184 | 0.02115 | 0.00389 | 0.01315 | 0.04087 | 0.5 | default | 300 | 10
Can you give me some advices? 
Thank you so much!

**Comment by 0215Arthur** [comment]
Hi~ I just try to get the splitted dataset you provided https://www.dropbox.com/s/th672ttebwxhsfx/CIKM2017.zip?dl=0 
Howerver, the zip file  failed to open and it showed that the file is wrong. Maybe the data is broken?
Could you give me some advices of getting the splitted data?
@evison

**Comment by evison** [comment]
@0215Arthur Thanks for inquiry. Some people also has similar problem. Usually it is because the machine used to unzip the file does not has sufficiently large memory, or because of the memory limit of commends if you are unzipping the file using a terminal. I would suggest you to unzip the file on a machine with larger memory, and use "jar xvf" command instead "unzip" command to unzip the file.

**Comment by 0215Arthur** [comment]
@evison OMG ! Thank you very much! I will have a try.
